name: Release Checks

on:
  push: {}

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Spider and check
        uses: filiph/linkcheck@2.0.23
        with:
          arguments: file:///

